Add main_svc
FisanovE/java-explore-with-me pull request #2
Opened 2024-01-22 13:11 UTC by FisanovE

feat: создать и настроить работу компонентов основного сервиса приложения, произвести рефакторинг сервиса статистики. Отладить совместную работу обоих модулей, в том числе и в docker-контейнере.

2024-01-24 04:41 UTC, krylov-sergey-sergeevich requested changes
Привет, отметил что можно улучшить

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesMapper.java
> +public class CategoriesMapper {
На будущее рекомендую почитать про mapstruct он в таких мапперах сильно помогает

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesServiceAdmin.java
> +       /* Optional<CategoryDto> categoryByName = categoriesRepository.findByName(categoryDto.getName());
Не рекомендуется хранить закомментированный код, лучше если не нужен удалять

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/model/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
`@Column(name = "id", nullable = false)`

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/model/Category.java
> +    @Column(name = "name", nullable = false)
`@Column(nullable = false, unique = true)`

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/compilations/model/Compilation.java
> +    @ManyToMany
`@ManyToMany(fetch = FetchType.LAZY)` - many to many тяжелая связь лучше ее Lazy иметь

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/compilations/model/Compilation.java
> +    private List<Event> events;
и обычно вот такие тяжелые поля идет в конце в ентити, после примитивных полей

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/events/EventsMapper.java
> +    private final CategoriesMapper categoriesMapper = new CategoriesMapper();
Это же бины почему не инжект а вот такое создание идет?

2024-01-24 04:41 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/users/UserController.java
> +public class UserController {
UserAdminController мжт быть?

2024-01-24 09:50 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesServiceAdmin.java
> +       /* Optional<CategoryDto> categoryByName = categoriesRepository.findByName(categoryDto.getName());
Исправлено.

2024-01-24 10:45 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/model/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Исправлено.

2024-01-24 10:46 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/model/Category.java
> +    @Column(name = "name", nullable = false)
Исправлено.

2024-01-24 10:46 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/compilations/model/Compilation.java
> +    @ManyToMany
Исправлено.

2024-01-24 10:46 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/compilations/model/Compilation.java
> +    private List<Event> events;
Исправлено.

2024-01-24 10:49 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/events/EventsMapper.java
> +    private final CategoriesMapper categoriesMapper = new CategoriesMapper();
Исправлено.

2024-01-24 10:53 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/users/UserController.java
> +public class UserController {
Исправлено.

2024-01-24 10:57 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesMapper.java
> +public class CategoriesMapper {
Слегка поглядел, на будущее изучу. Инструмент, довольно масштабный. В этом проекте, мне кажется, mapstruct слегка излишен, да и стараюсь всё делать без внедрения лишних зависимостей, базовыми средствами.

2024-01-25 06:42 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2024-01-25 06:42 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesService.java
> +        Category category = categoriesRepository.findById(id).orElseThrow(() -> new NotFoundException("Category not found: " + id));
new NotFoundException("Category not found: " + id) - на будущее рекомендую сразу создавать кастомное исключение чтобы текст не писать везде ручками, а он был 1 раз в конструкторе определен

2024-01-25 06:42 UTC, krylov-sergey-sergeevich commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesService.java
> +        Category category = categoriesRepository.findById(id).orElseThrow(() -> new NotFoundException("Category not found: " + id));
только в этом классе 3 раза повторяется

2024-01-25 08:18 UTC, FisanovE commented on ewm_service/src/main/java/ru/practicum/ewm/admin_api/categories/CategoriesService.java
> +        Category category = categoriesRepository.findById(id).orElseThrow(() -> new NotFoundException("Category not found: " + id));
Хорошо! Займусь этим после реализации фичи, если будет время.

2024-01-25 08:18 UTC, merged